apiVersion: v1
kind: ServiceAccount
metadata:
  name: rebac-api
  namespace: access-kit
  labels:
    app.kubernetes.io/name: rebac-api
    app.kubernetes.io/part-of: access-kit
automountServiceAccountToken: false
