apiVersion: v1
kind: Service
metadata:
  name: rebac-api
  namespace: access-kit
  labels:
    app.kubernetes.io/name: rebac-api
    app.kubernetes.io/part-of: access-kit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rebac-api
  ports:
    - name: http
      port: 3000
      targetPort: http
